// Inicializa o índice da pergunta
let questionIndex = 0;

// Perguntas e respostas corretas
const questions = [
    "Quem é Eliane Potiguara?\n a) Uma política brasileira\n b) Uma escritora e ativista indígena\n c) Uma artista plástica\n d) Uma cientista social",
        "Qual é a etnia de Eliane Potiguara?\n a) Guarani\n b) Tupinambá\n c) Potiguara\n d) Kayapó",
            "Em qual estado brasileiro Eliane Potiguara nasceu?\n a) Bahia\n b) Amazonas\n c) Paraíba\n d) Mato Grosso do Sul",
                "Qual é uma das principais contribuições de Eliane Potiguara para a literatura?\n a) Escrita de romances de ficção científica\n b) Publicação de livros que abordam a cultura indígena e questões sociais\n c) Desenvolvimento de livros didáticos para crianças\n d) Criação de poesias sobre a vida urbana",
                    "Eliane Potiguara é conhecida por sua atuação em que área além da literatura?\n a) Política\n b) Saúde\n c) Educação\n d) Direitos Humanos e ativismo indígena",
                        "Qual livro de Eliane Potiguara é uma das suas obras mais conhecidas?\n a) 'Mulheres da Terra'\n b) 'A Cor do Lamento'\n c) 'O Coração das Trevas'\n d) 'Terra das Águas'",
                            "Eliane Potiguara também é conhecida por seu trabalho como:\n a) Professora universitária\n b) Jornalista\n c) Palestrante e defensora dos direitos indígenas\n d) Artista de rua",
                                "Em qual contexto Eliane Potiguara escreveu suas obras?\n a) Somente em contextos urbanos\n b) Em contextos que misturam a experiência indígena e as questões contemporâneas\n c) Exclusivamente sobre a vida na cidade\n d) Somente sobre a natureza e meio ambiente",
                                    "Eliane Potiguara é um exemplo de:\n a) Ativismo cultural e político indígena\n b) Esportista internacional\n c) Empresária de sucesso\n d) Cientista renomada",
                                        "Qual foi uma das principais temáticas abordadas por Eliane Potiguara em seus escritos?\n a) Tecnologia e inovação\n b) Experiência indígena e resistência cultural\n c) História medieval\n d) Economia e finanças"
                                        ];

                                        const correctAnswers = ["b", "c", "c", "b", "d", "a", "c", "b", "a", "b"];

                                        // Função para exibir a pergunta atual
                                        function showQuestion() {
                                            if (questionIndex < questions.length) {
                                                    player.say(questions[questionIndex]);
                                                        } else {
                                                                player.say("Obrigado por participar do questionário! Você completou todas as perguntas.");
                                                                    }
                                                                    }

                                                                    // Função para verificar a resposta fornecida
                                                                    function checkAnswer(answer) {
                                                                        if (answer.toLowerCase() === correctAnswers[questionIndex]) {
                                                                                player.say("Resposta correta!");
                                                                                        // Adiciona um bloco de ouro para indicar que a resposta foi correta
                                                                                                let pos = player.position();
                                                                                                        blocks.place("gold_block", pos.add(1, 0, 0));
                                                                                                            } else {
                                                                                                                    player.say("Resposta errada. Tente novamente!");
                                                                                                                        }
                                                                                                                            // Avança para a próxima pergunta
                                                                                                                                questionIndex++;
                                                                                                                                    showQuestion();
                                                                                                                                    }

                                                                                                                                    // Função para iniciar o questionário
                                                                                                                                    function onStart() {
                                                                                                                                        player.say("Bem-vindo ao questionário sobre Eliane Potiguara! Entre nas cabanas para responder às perguntas.");
                                                                                                                                            player.setGameMode(SURVIVAL);  // Define o jogador no modo Aventura
                                                                                                                                                createQuizHuts();
                                                                                                                                                }

                                                                                                                                                // Função para criar cabanas de quiz
                                                                                                                                                function createQuizHuts() {
                                                                                                                                                    let hutLocations = [
                                                                                                                                                            { x: 10, y: 4, z: 10 },
                                                                                                                                                                    { x: 20, y: 4, z: 10 },
                                                                                                                                                                            { x: 30, y: 4, z: 10 },
                                                                                                                                                                                    { x: 40, y: 4, z: 10 },
                                                                                                                                                                                            { x: 50, y: 4, z: 10 },
                                                                                                                                                                                                    { x: 60, y: 4, z: 10 },
                                                                                                                                                                                                            { x: 70, y: 4, z: 10 },
                                                                                                                                                                                                                    { x: 80, y: 4, z: 10 },
                                                                                                                                                                                                                            { x: 90, y: 4, z: 10 },
                                                                                                                                                                                                                                    { x: 100, y: 4, z: 10 }
                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                            for (let i = 0; i < hutLocations.length; i++) {
                                                                                                                                                                                                                                                    let pos = new Position(hutLocations[i].x, hutLocations[i].y, hutLocations[i].z);
                                                                                                                                                                                                                                                            // Cria a estrutura básica da cabana
                                                                                                                                                                                                                                                                    blocks.fill(pos, pos.add(5, 5, 5), "wood");
                                                                                                                                                                                                                                                                            blocks.fill(pos.add(1, 1, 1), pos.add(4, 4, 4), "air");
                                                                                                                                                                                                                                                                                    // Coloca um bloco de sinalização dentro para indicar a pergunta
                                                                                                                                                                                                                                                                                            blocks.place("sign", pos.add(2, 2, 2));
                                                                                                                                                                                                                                                                                                    player.say(`Cabana ${i + 1} criada na posição ${pos.getValue(Axis.X)}, ${pos.getValue(Axis.Y)}, ${pos.getValue(Axis.Z)}`);
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                        // Função para lidar com o clique em uma cabana
                                                                                                                                                                                                                                                                                                        function onCabanaClick(x, y, z) {
                                                                                                                                                                                                                                                                                                            // Identifica a pergunta associada à cabana clicada
                                                                                                                                                                                                                                                                                                                let hutIndex = Math.floor((x - 10) / 10);
                                                                                                                                                                                                                                                                                                                    if (hutIndex < questions.length) {
                                                                                                                                                                                                                                                                                                                            player.say(questions[hutIndex]);
                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                        player.say("Esta cabana não está associada a nenhuma pergunta.");
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                            // Função para responder perguntas
                                                                                                                                                                                                                                                                                                                                            player.onChat(function (message) {
                                                                                                                                                                                                                                                                                                                                                // Verifica se a mensagem começa com "resposta "
                                                                                                                                                                                                                                                                                                                                                    if (message.startsWith("resposta ")) {
                                                                                                                                                                                                                                                                                                                                                            // Extrai a resposta da mensagem
                                                                                                                                                                                                                                                                                                                                                                    let answer = message.substring(8).trim();
                                                                                                                                                                                                                                                                                                                                                                            // Verifica a resposta
                                                                                                                                                                                                                                                                                                                                                                                    checkAnswer(answer);
                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                player.say("Por favor, responda com o formato 'resposta <sua resposta>'.");
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                    // Evento de interação com a cabana
                                                                                                                                                                                                                                                                                                                                                                                                    player.onItemInteracted(function (block) {
                                                                                                                                                                                                                                                                                                                                                                                                        let pos = block.position();
                                                                                                                                                                                                                                                                                                                                                                                                            onCabanaClick(pos.getValue(Axis.X), pos.getValue(Axis.Y), pos.getValue(Axis.Z));
                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                            // Inicia o script
                                                                                                                                                                                                                                                                                                                                                                                                            onStart();